# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='iban',
            field=localflavor.generic.models.IBANField(include_countries=None, max_length=34, null=True, use_nordea_extensions=False),
        ),
    ]
